# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTOmkjdkSDPk-e3Ct4SVJqlrI2QLGzkJ
"""

# Install OpenCV if not already installed

73

!pip install opencv-python-headless --quiet
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload an image
print("Upload a grayscale or color image (e.g., texture, face, fingerprint):")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
# Step 2: Read the image in grayscale
gray = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
# Step 3: Create Gabor kernel
kernel = cv2.getGaborKernel(ksize=(21, 21), sigma=8.0, theta=np.pi/4, lambd=10.0, gamma=0.5,
psi=0, ktype=cv2.CV_32F)
# Step 4: Apply Gabor filter
filtered = cv2.filter2D(gray, cv2.CV_8UC3, kernel)
# Step 5: Display original and filtered images side-by-side
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title('Original Image')
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(filtered, cmap='gray')
plt.title('Gabor Filtered Image')
plt.axis('off')
plt.show()

# Install OpenCV if not installed
!pip install opencv-python-headless --quiet
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload an image
print("Upload a grayscale or color image (texture, face, fingerprint, fabric, etc.):")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

75

# Step 2: Read image in grayscale
gray = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
# Step 3: Define orientations and apply Gabor filters
orientations = [0, np.pi/4, np.pi/2, 3*np.pi/4]
plt.figure(figsize=(16, 5))
for i, theta in enumerate(orientations):
    kernel = cv2.getGaborKernel((21, 21), 4.0, theta, 10.0, 0.5, 0, ktype=cv2.CV_32F)
    filtered_img = cv2.filter2D(gray, cv2.CV_8UC3, kernel)
    plt.subplot(1, 4, i+1)
    plt.imshow(filtered_img, cmap='gray')
    plt.title(f"Orientation {int(np.degrees(theta))}°")
    plt.axis('off')
plt.suptitle('Gabor Filtering at Multiple Orientations', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

# Install OpenCV if not installed
!pip install opencv-python-headless --quiet
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload fingerprint image
print("Upload a fingerprint image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
# Step 2: Read the fingerprint image in grayscale
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
# Check image loaded
if img is None:
    print("Error loading image.")
else:
    # Step 3: Define Gabor filter parameters (typical for fingerprint ridge enhancement)
    kernel_size = 21
    sigma = 5.0 # Standard deviation of the gaussian envelope
    lambd = 10.0 # Wavelength of the sinusoidal factor
    gamma = 0.5 # Spatial aspect ratio
    psi = 0 # Phase offset
    # Apply Gabor filters at multiple orientations to capture ridge directions
    orientations = [0, np.pi/4, np.pi/2, 3*np.pi/4]
    filtered_imgs = []
    plt.figure(figsize=(12, 6))
    plt.subplot(1, len(orientations)+1, 1)
    plt.title("Original Fingerprint")
    plt.imshow(img, cmap='gray')
    plt.axis('off')
    for i, theta in enumerate(orientations):
        kernel = cv2.getGaborKernel((kernel_size, kernel_size), sigma, theta, lambd, gamma, psi,
                                    ktype=cv2.CV_32F)
        filtered_img = cv2.filter2D(img, cv2.CV_8UC3, kernel)

        filtered_imgs.append(filtered_img)
        plt.subplot(1, len(orientations)+1, i+2)
        plt.title(f"Orientation {int(np.degrees(theta))}°")
        plt.imshow(filtered_img, cmap='gray')
        plt.axis('off')
    plt.tight_layout()
    plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

def gabor_features(img, kernels):
    """Extract Gabor features from an image using multiple kernels."""
    features = []
    for kernel in kernels:
        filtered = cv2.filter2D(img, cv2.CV_8UC3, kernel)
        mean = filtered.mean()
        variance = filtered.var()
        features.extend([mean, variance])
    return features

# Step 1: Upload a single image
print("Upload a single image (e.g., texture, face, fingerprint):")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Step 2: Read the image in grayscale
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

if img is None:
    print(f"Error: Could not load image from {image_path}")
else:
    # Step 3: Create Gabor kernels at different orientations and frequencies
    kernel_size = 21
    sigmas = [4.0, 6.0]
    lambdas = [10.0, 15.0]
    gammas = [0.5]
    psis = [0]
    orientations = [0, np.pi/4, np.pi/2, 3*np.pi/4]
    kernels = []
    for sigma in sigmas:
        for lambd in lambdas:
            for gamma in gammas:
                for psi in psis:
                    for theta in orientations:
                        kernel = cv2.getGaborKernel((kernel_size, kernel_size), sigma, theta, lambd, gamma,
                                                psi, ktype=cv2.CV_32F)
                        kernels.append(kernel)

    # Step 4: Extract Gabor features from the uploaded image
    extracted_features = gabor_features(img, kernels)
    print(f"\nExtracted Gabor Features for '{image_path}':")
    print(extracted_features)

    # Optional: Display the original image and some filtered versions for visual inspection
    plt.figure(figsize=(12, 6))
    plt.subplot(1, 2, 1)
    plt.imshow(img, cmap='gray')
    plt.title('Original Image')
    plt.axis('off')

    if kernels:
        # Apply one of the Gabor filters and display it
        example_filtered_img = cv2.filter2D(img, cv2.CV_8UC3, kernels[0])
        plt.subplot(1, 2, 2)
        plt.imshow(example_filtered_img, cmap='gray')
        plt.title('Example Gabor Filtered Image')
        plt.axis('off')
    plt.show()